# Configuración principal del framework de automatización
# Framework desarrollado por el equipo de QA de Kernotec

# Configuración de la aplicación
app:
  name: "Selenium Automation Framework"
  version: "1.0.0"
  description: "Framework de automatización web para Kernotec"

# Configuración de entornos
environments:
  dev:
    baseUrl: "https://dev.example.com"
    apiUrl: "https://dev-api.example.com"
  test:
    baseUrl: "https://test.example.com"
    apiUrl: "https://test-api.example.com"
  prod:
    baseUrl: "https://prod.example.com"
    apiUrl: "https://prod-api.example.com"

# Configuración de testing
testing:
  environment: "test"
  parallel: true
  threadCount: 3
  retryCount: 2
  dataProvider:
    strategy: "excel" # excel, json, csv
    path: "src/test/resources/testdata/"

# Configuración de browsers
browser:
  default: "chrome"
  headless: false
  window:
    width: 1920
    height: 1080
  options:
    chrome:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--disable-extensions"
      - "--disable-popup-blocking"
      - "--disable-notifications"
      - "--remote-allow-origins=*"
      - "--disable-web-security"
      - "--allow-running-insecure-content"
    firefox:
      preferences:
        dom.webnotifications.enabled: false
        media.navigator.permission.disabled: true
        dom.push.enabled: false
        geo.enabled: false

# Configuración de timeouts
timeouts:
  implicit: 10
  explicit: 30
  pageLoad: 60
  script: 30
  polling: 500

# Configuración de usuarios de prueba
users:
  admin:
    username: "admin@kernotec.com"
    password: "Admin123!"
    role: "administrator"
    permissions: ["read", "write", "delete", "admin"]
  testuser:
    username: "testuser@kernotec.com"
    password: "Test123!"
    role: "user"
    permissions: ["read", "write"]
  readonly:
    username: "readonly@kernotec.com"
    password: "ReadOnly123!"
    role: "viewer"
    permissions: ["read"]

# Configuración de características del framework
features:
  screenshots: true
  videoRecording: false
  apiTesting: true
  databaseTesting: false
  mobileTesting: false
  performanceTesting: false

# Configuración de reportes
reporting:
  extentReports:
    enabled: true
    path: "test-output/extent-reports/"
    title: "Kernotec Automation Report"
    theme: "standard" # standard, dark
  testngReports:
    enabled: true
    path: "test-output/testng-reports/"
  screenshots:
    enabled: true
    path: "test-output/screenshots/"
    onFailure: true
    onSuccess: false

# Configuración de logging
logging:
  level: "INFO" # DEBUG, INFO, WARN, ERROR
  file:
    enabled: true
    path: "test-output/logs/"
    maxSize: "10MB"
    maxFiles: 5
  console:
    enabled: true

# Configuración de base de datos (opcional)
database:
  enabled: false
  type: "mysql"
  host: "localhost"
  port: 3306
  name: "testdb"
  username: "testuser"
  password: "testpass"

# Configuración de API (opcional)
api:
  baseUrl: "https://api.example.com"
  timeout: 30
  retryCount: 3
  headers:
    Content-Type: "application/json"
    Accept: "application/json"

# Configuración de email (para notificaciones)
email:
  enabled: false
  smtp:
    host: "smtp.gmail.com"
    port: 587
    username: "automation@kernotec.com"
    password: "password"
  recipients:
    - "qa-team@kernotec.com"
    - "dev-team@kernotec.com"
